baseURL = "https://kuangqike.pages.dev/"
locale = "zh-CN"
title = "匡齐"
theme = "PaperMod"

[params]
  description = "运动、认知、做事，在世界上留下痕迹。"
  author = "匡齐"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "工具"
    url = "/works/"
    weight = 2
  [[menu.main]]
    name = "案例"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true
